name: newsblog_prokit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Base
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.4
  intl: ^0.19.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  #News Blog
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.3
  image_picker: ^1.0.0
  path_drawing: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/
